import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Clock from "./components/Clock";

const poppins = Poppins({ weight: ["300", "400", "600", "700", "900"], subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme={"winter"}>
      <body className={poppins.className}>
        <Clock />
        {children}
      </body>
    </html>
  );
}
